version: "3.4"
services:
  mealio:
    container_name: mealio
    image: node:18
    command: npm install -g firebase-tools
    working_dir: /var/www/html/app
    entrypoint: /bin/bash
    ports:
      - "8000:8000"
      - "9005:9005"
    volumes:
      - ./:/var/www/html/app
    tty: true